# Generated by Django 4.1.3 on 2023-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instname', models.CharField(max_length=100)),
                ('inst_id', models.IntegerField(null=True)),
                ('principal', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='orgname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
