# Generated by Django 4.1.3 on 2023-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_table_instname_user_instname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='principal',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
